# Generated by Django 3.1.5 on 2022-10-27 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BokuPayment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "charging_token",
                    models.CharField(blank=True, max_length=65, unique=True),
                ),
                ("authorisation_state", models.CharField(blank=True, max_length=20)),
                ("operation_reference", models.CharField(max_length=65, unique=True)),
                ("consumer_identity", models.CharField(blank=True, max_length=65)),
                ("latest_update", models.DateTimeField(blank=True)),
                ("billing_identity", models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name="BokuPaymentError",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.CharField(max_length=155)),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="errors",
                        to="payments.bokupayment",
                    ),
                ),
            ],
        ),
    ]
