# Generated by Django 3.1.5 on 2022-10-28 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_auto_20221027_1720"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bokupayment",
            name="latest_update",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
