# Generated by Django 3.1.5 on 2022-10-29 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0005_auto_20221028_1943"),
    ]

    operations = [
        migrations.CreateModel(
            name="Charges",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transaction_id", models.CharField(max_length=155)),
                ("transaction_state", models.CharField(max_length=65)),
                ("latest_update", models.DateTimeField(blank=True, null=True)),
                ("price", models.FloatField()),
                (
                    "payment",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="charges",
                        to="payments.bokupayment",
                    ),
                ),
            ],
        ),
    ]
