# Generated by Django 3.1.5 on 2022-11-01 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0008_chargeerror"),
    ]

    operations = [
        migrations.AlterField(
            model_name="charge",
            name="price",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
