# Generated by Django 3.1.5 on 2022-11-01 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0009_auto_20221101_1841"),
    ]

    operations = [
        migrations.CreateModel(
            name="Refund",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("operation_reference", models.CharField(max_length=155)),
                ("refund_reason", models.TextField(blank=True)),
                ("refund_status", models.CharField(blank=True, max_length=155)),
                ("amount", models.FloatField(blank=True, null=True)),
                ("transaction_id", models.CharField(max_length=155)),
                ("latest_update", models.DateTimeField(blank=True, null=True)),
                (
                    "payment",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="refunds",
                        to="payments.bokupayment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RefundError",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.CharField(max_length=155)),
                (
                    "refund",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="errors",
                        to="payments.refund",
                    ),
                ),
            ],
        ),
    ]
