# Generated by Django 3.1.5 on 2022-11-03 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0010_refund_refunderror"),
    ]

    operations = [
        migrations.CreateModel(
            name="Operator",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=95)),
                ("code", models.CharField(max_length=95)),
                ("country", models.CharField(max_length=65)),
                ("country_id", models.CharField(max_length=5)),
                ("max_transaction_limit", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Msdin",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pattern", models.CharField(max_length=55)),
                (
                    "operator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="msdins",
                        to="payments.operator",
                    ),
                ),
            ],
        ),
    ]
