# Generated by Django 3.1.5 on 2022-11-03 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0011_msdin_operator"),
    ]

    operations = [
        migrations.AddField(
            model_name="operator",
            name="currency",
            field=models.CharField(default="euro", max_length=65),
        ),
    ]
