# Generated by Django 3.1.5 on 2022-12-16 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("payments", "0013_bokupayment_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="privatekey",
            name="payment_gateway",
            field=models.CharField(
                choices=[("boku", "Boku"), ("stripe", "Stripe")], max_length=65
            ),
        ),
        migrations.AlterField(
            model_name="publickey",
            name="payment_gateway",
            field=models.CharField(
                choices=[("boku", "Boku"), ("stripe", "Stripe")], max_length=65
            ),
        ),
        migrations.CreateModel(
            name="StripeIntent",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("status", models.CharField(max_length=255)),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        blank=True, default=None, max_length=50, null=True
                    ),
                ),
                ("intent_id", models.CharField(blank=True, max_length=255)),
                ("payment_method_id", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
