# Generated by Django 3.1.5 on 2022-12-16 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0014_auto_20221216_1306"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stripeintent",
            name="payment_method_id",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
