# Generated by Django 3.1.5 on 2022-12-20 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0016_paypalorder"),
    ]

    operations = [
        migrations.AlterField(
            model_name="privatekey",
            name="payment_gateway",
            field=models.CharField(
                choices=[("boku", "Boku"), ("stripe", "Stripe"), ("paypal", "PayPal")],
                max_length=65,
            ),
        ),
        migrations.AlterField(
            model_name="publickey",
            name="payment_gateway",
            field=models.CharField(
                choices=[("boku", "Boku"), ("stripe", "Stripe"), ("paypal", "PayPal")],
                max_length=65,
            ),
        ),
    ]
