# Generated by Django 3.1.5 on 2022-12-20 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0017_auto_20221220_1110"),
    ]

    operations = [
        migrations.AddField(
            model_name="paypalorder",
            name="customer_email",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="paypalorder",
            name="customer_id",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
