# Generated by Django 3.1.5 on 2022-12-23 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0018_auto_20221220_1310"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="paypalorder",
            options={
                "verbose_name": "PayPal Order",
                "verbose_name_plural": "PayPal Orders",
            },
        ),
        migrations.AlterModelOptions(
            name="stripeintent",
            options={
                "verbose_name": "Stripe Order",
                "verbose_name_plural": "Stripe Orders",
            },
        ),
    ]
