# Generated by Django 3.1.5 on 2022-12-30 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0019_auto_20221223_1439"),
    ]

    operations = [
        migrations.AddField(
            model_name="stripeintent",
            name="charge_id",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
