# Generated by Django 3.1.5 on 2022-12-30 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0020_stripeintent_charge_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="stripeintent",
            name="is_refunded",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="stripeintent",
            name="refunded_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
