# Generated by Django 3.1.5 on 2023-01-02 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0021_auto_20221230_1357"),
    ]

    operations = [
        migrations.CreateModel(
            name="StripeRefund",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "refund_reason",
                    models.CharField(
                        blank=True, default=None, max_length=255, null=True
                    ),
                ),
                (
                    "refund_status",
                    models.CharField(
                        blank=True, default=None, max_length=100, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("udated_at", models.DateTimeField(auto_now=True)),
                (
                    "intent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payments.stripeintent",
                    ),
                ),
            ],
        ),
    ]
