# Generated by Django 3.1.5 on 2023-02-02 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0022_striperefund"),
    ]

    operations = [
        migrations.CreateModel(
            name="SetAllowedPaymentMethods",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payment_method", models.CharField(max_length=100)),
                ("is_allowed", models.BooleanField(default=True)),
            ],
        ),
    ]
