# Generated by Django 3.1.5 on 2023-03-15 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0064_auto_20230308_1101'),
        ('payments', '0023_setallowedpaymentmethods'),
    ]

    operations = [
        migrations.AddField(
            model_name='setallowedpaymentmethods',
            name='hide_for',
            field=models.ManyToManyField(blank=True, to='user.Country'),
        ),
    ]
