# Generated by Django 3.1.5 on 2023-03-16 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0064_auto_20230308_1101'),
        ('payments', '0024_setallowedpaymentmethods_hide_for'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setallowedpaymentmethods',
            name='hide_for',
        ),
        migrations.CreateModel(
            name='SetPaymentMethodRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('countries', models.ManyToManyField(to='user.Country')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentGatewayForRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_allowed', models.BooleanField(default=True)),
                ('payment_gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.setallowedpaymentmethods')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.setpaymentmethodregion')),
            ],
        ),
    ]
