# pull official base image
FROM python:3.9.12

ARG APP_HOME=/home/i69
RUN apt update
RUN apt-get update \
  && apt-get install --no-install-recommends --yes supervisor nginx
RUN apt-get install tesseract-ocr -y

# accept arguments
ARG PIP_REQUIREMENTS=requirements.txt

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# install dependencies
RUN pip install --upgrade pip setuptools

# set work directory
WORKDIR ${APP_HOME}

COPY requirements.txt .
RUN pip3 install -r requirements.txt
RUN pip3 install opennsfw2==0.10.2
RUN pip3 install opencv-python-headless==4.5.3.56
COPY ./docker/.conf.d/supervisor/supervisord.conf.dev /etc/supervisor/supervisord.conf
COPY ./docker/.conf.d/nginx/nginx.conf /etc/nginx/nginx.conf
COPY ./docker/.conf.d/nginx/i69.conf.dev /etc/nginx/conf.d/default.conf
#COPY ./media ${APP_HOME}/media
# create supervisor socket directory
RUN mkdir -p /home/i69/env/run/supervisor


ENTRYPOINT ["/bin/bash","/home/i69/docker/entrypoint.sh"]
