# Generated by Django 3.1.5 on 2022-01-22 07:02

from django.db import migrations, models
import moments.models


class Migration(migrations.Migration):

    dependencies = [
        ("moments", "0004_auto_20220122_1231"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moment",
            name="file",
            field=models.FileField(
                blank=True,
                max_length=1000,
                null=True,
                upload_to=moments.models.Moment.get_avatar_path,
            ),
        ),
    ]
