# Generated by Django 3.1.5 on 2022-03-18 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moments", "0008_storydeletiontime"),
    ]

    operations = [
        migrations.AddField(
            model_name="storydeletiontime",
            name="text",
            field=models.CharField(default="Click to change", max_length=20),
        ),
        migrations.AlterField(
            model_name="storydeletiontime",
            name="days",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="storydeletiontime",
            name="hours",
            field=models.DecimalField(decimal_places=2, default=24.0, max_digits=2),
        ),
        migrations.AlterField(
            model_name="storydeletiontime",
            name="weeks",
            field=models.IntegerField(default=0),
        ),
    ]
