# Generated by Django 3.1.5 on 2022-03-18 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moments", "0009_auto_20220318_2123"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storydeletiontime",
            name="text",
            field=models.CharField(
                default="Click to change", max_length=20, verbose_name=" "
            ),
        ),
    ]
