# Generated by Django 3.1.5 on 2022-03-19 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moments", "0010_auto_20220318_2127"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storydeletiontime",
            name="hours",
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
    ]
