# Generated by Django 3.1.5 on 2022-03-23 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moments", "0012_auto_20220319_2206"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="created_date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="storydeletiontime",
            name="days",
            field=models.IntegerField(default=3),
        ),
    ]
