# Generated by Django 3.1.5 on 2022-03-23 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moments", "0013_auto_20220323_1517"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storydeletiontime",
            name="hours",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
    ]
