# Generated by Django 3.1.5 on 2022-03-23 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("moments", "0014_auto_20220323_1839"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="reply_to",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parent_comment",
                to="moments.comment",
            ),
        ),
    ]
