# Generated by Django 3.1.5 on 2022-04-06 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("moments", "0017_commentlike"),
    ]

    operations = [
        migrations.DeleteModel(
            name="StoryDeletionTime",
        ),
    ]
