# Generated by Django 3.1.5 on 2022-04-15 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moments", "0020_auto_20220415_1827"),
    ]

    operations = [
        migrations.AddField(
            model_name="genericcomment",
            name="comment_description",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="genericcomment",
            name="created_date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
