# Generated by Django 3.1.5 on 2022-04-15 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moments", "0021_auto_20220415_1928"),
    ]

    operations = [
        migrations.CreateModel(
            name="StoryVisibleTime",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.CharField(
                        default="Click to change", max_length=20, verbose_name=" "
                    ),
                ),
                ("weeks", models.IntegerField(default=0)),
                ("days", models.IntegerField(default=3)),
                (
                    "hours",
                    models.DecimalField(decimal_places=2, max_digits=2, null=True),
                ),
            ],
        ),
    ]
