# Generated by Django 3.1.5 on 2022-04-24 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("moments", "0022_storyvisibletime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="reply_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parent_comment",
                to="moments.comment",
            ),
        ),
    ]
