# Generated by Django 3.1.5 on 2022-12-01 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import moments.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("moments", "0027_reviewstory"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReviewMoment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, null=True)),
                ("moment_description", models.TextField()),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=moments.models.ReviewMoment.get_file_review_avatar_path,
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[("image", "image"), ("video", "video")], max_length=10
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
