# Generated by Django 3.1.5 on 2022-12-03 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moments", "0028_reviewmoment"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviewmoment",
            name="prediction_score",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="reviewstory",
            name="prediction_score",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
    ]
