# Generated by Django 3.1.5 on 2023-02-16 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('moments', '0029_auto_20221203_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='moment',
            name='allow_comment',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='ReportComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Report_msg', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_for_report', to='moments.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User_for_report_comment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
