# Generated by Django 3.1.5 on 2023-12-23 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moments', '0031_auto_20230813_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='moment',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='moment',
            name='publish_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='story',
            name='publish_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
