version: "3.7"
x-logging: &logging
  logging:
    driver: loki
    options:
      loki-url: "http://localhost:3100/loki/api/v1/push"
services:
  web:
    image: 500255737853.dkr.ecr.eu-west-3.amazonaws.com/dev-i69api-web:_IMAGE_TAG
    container_name: web
    hostname: i69api
    restart: on-failure
    ports:
      - "9082:80"
    env_file:
      - ${ENV_FILE}
    depends_on:
      - postgres
      - redis
    networks:
      - i69_net
  
  redis:
    image: 500255737853.dkr.ecr.eu-west-3.amazonaws.com/dev-i69api-redis:_IMAGE_TAG
    container_name: redis
    hostname: redis
    restart: on-failure
    networks:
      - i69_net
      
  postgres:
    image: postgres:13.6-alpine3.15
    container_name: postgres
    hostname: postgres
    restart: on-failure
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_recover:/var/lib/postgresql/data
    env_file:
      - ${ENV_FILE}
    networks:
      - i69_net

networks:
  i69_net:

volumes:
  postgres_data_recover:
    external: true
    name: postgres_postgres_data_recover
