version: "3.7"
x-logging: &logging
  logging:
    driver: loki
    options:
      loki-url: "http://localhost:3100/loki/api/v1/push"
services:
  web:
    image: ${CI_REGISTRY_IMAGE:-i69}/${IMAGE:-web}:${SANITIZED_BRANCH:-latest}
    build:
      context: .
      dockerfile: ./docker/django/prod/Dockerfile.web
      args:
        UID: ${UID:-10600}
        GID: ${GID:-10600}
        UNAME: ${UNAME:-i69}
    container_name: web
    ports:
      - "9082:80"
      - "9081:80"
    hostname: web
    volumes:
      - media_volume:/home/i69/media
      - ./:/home/i69
    env_file:
      - ${ENV_FILE}
    depends_on:
      redis:
        condition: "service_healthy"
      postgres:
        condition: "service_started"
    networks:
      - i69_net
    restart: always

  postgres:
    image: postgres:13.6-alpine3.15
    container_name: postgres
    hostname: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ${ENV_FILE}
    networks:
      - i69_net
    restart: "no"

  redis:
    image: ${CI_REGISTRY_IMAGE:-i69}/${IMAGE:-redis}:${SANITIZED_BRANCH:-latest}
    build:
      context: .
      dockerfile: ./docker/redis/Dockerfile
    container_name: redis
    hostname: redis
    volumes:
      - redis_data:/data
    networks:
      - i69_net
    restart: "no"
    healthcheck:
      test: ["CMD", "redis-cli", "--user", "i69_redis", "--pass", "y4pFPrDBeTLs6_ac", "-c", "ping", "|" ,"grep PONG"]
      interval: 10s
      timeout: 5s
      retries: 3
networks:
  i69_net:


volumes:
  postgres_data:
  redis_data:
  media_volume:
