# Generated by Django 3.1.5 on 2022-01-24 11:41

from django.db import migrations, models
import gifts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Gift",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gift_name", models.CharField(max_length=100)),
                ("cost", models.FloatField()),
                (
                    "picture",
                    models.ImageField(upload_to=gifts.models.Gift.get_avatar_path),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("1", "real_gift"), ("2", "virtual_gift")],
                        max_length=1,
                    ),
                ),
            ],
        ),
    ]
