# Generated by Django 3.1.5 on 2022-01-24 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gifts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gift",
            name="type",
            field=models.CharField(
                choices=[("real", "real_gift"), ("virtual", "virtual_gift")],
                max_length=7,
            ),
        ),
    ]
