# Generated by Django 3.1.5 on 2022-01-25 04:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("gifts", "0002_auto_20220124_1740"),
    ]

    operations = [
        migrations.CreateModel(
            name="Giftpurchase",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gift_for_giftpurchase",
                        to="gifts.gift",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_for_giftpurchase",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
