# Generated by Django 3.1.5 on 2022-01-26 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("gifts", "0003_giftpurchase"),
    ]

    operations = [
        migrations.AddField(
            model_name="giftpurchase",
            name="receiver",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="receiver_for_giftpurchase",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
