# Generated by Django 3.1.5 on 2022-04-07 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gifts", "0004_giftpurchase_receiver"),
    ]

    operations = [
        migrations.AddField(
            model_name="giftpurchase",
            name="purchased_on",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
