# Generated by Django 3.1.5 on 2022-04-24 07:45

from django.db import migrations, models
import gifts.models


class Migration(migrations.Migration):

    dependencies = [
        ("gifts", "0006_auto_20220407_2121"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gift",
            name="picture",
            field=models.ImageField(
                blank=True, upload_to=gifts.models.Gift.get_avatar_path
            ),
        ),
    ]
