# Generated by Django 3.1.5 on 2022-10-19 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gifts", "0007_auto_20220424_1315"),
    ]

    operations = [
        migrations.AddField(
            model_name="gift",
            name="gift_name_fr",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
