# Generated by Django 3.1.5 on 2022-11-19 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gifts", "0009_auto_20221118_1055"),
    ]

    operations = [
        migrations.AddField(
            model_name="gift",
            name="gift_name_am",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="gift",
            name="gift_name_az",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="gift",
            name="gift_name_be",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="gift",
            name="gift_name_bg",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="gift",
            name="gift_name_bn",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="gift",
            name="gift_name_bs",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="gift",
            name="gift_name_ca",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="gift",
            name="gift_name_et",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="gift",
            name="gift_name_eu",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="gift",
            name="gift_name_gl",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="gift",
            name="gift_name_hy",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="gift",
            name="gift_name_ka",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="gift",
            name="gift_name_km",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="gift",
            name="gift_name_la",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="gift",
            name="gift_name_lv",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="gift",
            name="gift_name_sq",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="gift",
            name="gift_name_th",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
    ]
