# Generated by Django 3.1.5 on 2022-11-23 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gifts", "0010_auto_20221119_0914"),
    ]

    operations = [
        migrations.AddField(
            model_name="gift",
            name="gift_name_ga",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="gift",
            name="gift_name_hi",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="gift",
            name="gift_name_hu",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="gift",
            name="gift_name_id",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="gift",
            name="gift_name_is",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="gift",
            name="gift_name_mk",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="gift",
            name="gift_name_mn",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="gift",
            name="gift_name_ne",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="gift",
            name="gift_name_ro",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="gift",
            name="gift_name_sk",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="gift",
            name="gift_name_sr",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="gift",
            name="gift_name_ta",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="gift",
            name="gift_name_tg",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="gift",
            name="gift_name_tr",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="gift",
            name="gift_name_ur",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="gift",
            name="gift_name_uz",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
    ]
