# Generated by Django 3.1.5 on 2022-11-23 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gifts", "0011_auto_20221123_0953"),
    ]

    operations = [
        migrations.CreateModel(
            name="GiftPurchaseMessageText",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=5000)),
            ],
        ),
    ]
