# Generated by Django 3.1.5 on 2022-11-25 12:16

from django.db import migrations, models
import gifts.models


class Migration(migrations.Migration):

    dependencies = [
        ("gifts", "0012_giftpurchasemessagetext"),
    ]

    operations = [
        migrations.CreateModel(
            name="RealGift",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gift_name", models.CharField(max_length=100)),
                ("cost", models.FloatField()),
                (
                    "picture",
                    models.ImageField(
                        blank=True, upload_to=gifts.models.AbstractGift.get_avatar_path
                    ),
                ),
                ("gift_name_fr", models.CharField(max_length=100)),
                (
                    "gift_name_zh_cn",
                    models.CharField(blank=True, max_length=265, null=True),
                ),
                (
                    "gift_name_nl",
                    models.CharField(blank=True, max_length=265, null=True),
                ),
                (
                    "gift_name_de",
                    models.CharField(blank=True, max_length=265, null=True),
                ),
                (
                    "gift_name_sw",
                    models.CharField(blank=True, max_length=265, null=True),
                ),
                (
                    "gift_name_it",
                    models.CharField(blank=True, max_length=265, null=True),
                ),
                (
                    "gift_name_ar",
                    models.CharField(blank=True, max_length=265, null=True),
                ),
                (
                    "gift_name_iw",
                    models.CharField(blank=True, max_length=265, null=True),
                ),
                (
                    "gift_name_ja",
                    models.CharField(blank=True, max_length=265, null=True),
                ),
                (
                    "gift_name_ru",
                    models.CharField(blank=True, max_length=265, null=True),
                ),
                (
                    "gift_name_fa",
                    models.CharField(blank=True, max_length=265, null=True),
                ),
                (
                    "gift_name_pt_br",
                    models.CharField(blank=True, max_length=265, null=True),
                ),
                (
                    "gift_name_pt_pt",
                    models.CharField(blank=True, max_length=265, null=True),
                ),
                (
                    "gift_name_es",
                    models.CharField(blank=True, max_length=265, null=True),
                ),
                (
                    "gift_name_el",
                    models.CharField(blank=True, max_length=265, null=True),
                ),
                (
                    "gift_name_zh_tw",
                    models.CharField(blank=True, max_length=265, null=True),
                ),
                (
                    "gift_name_uk",
                    models.CharField(blank=True, max_length=265, null=True),
                ),
                (
                    "gift_name_ko",
                    models.CharField(blank=True, max_length=265, null=True),
                ),
                (
                    "gift_name_pl",
                    models.CharField(blank=True, max_length=265, null=True),
                ),
                (
                    "gift_name_vi",
                    models.CharField(blank=True, max_length=265, null=True),
                ),
                (
                    "gift_name_no",
                    models.CharField(blank=True, max_length=265, null=True),
                ),
                (
                    "gift_name_sv",
                    models.CharField(blank=True, max_length=265, null=True),
                ),
                (
                    "gift_name_hr",
                    models.CharField(blank=True, max_length=265, null=True),
                ),
                (
                    "gift_name_cs",
                    models.CharField(blank=True, max_length=265, null=True),
                ),
                (
                    "gift_name_da",
                    models.CharField(blank=True, max_length=265, null=True),
                ),
                (
                    "gift_name_tl",
                    models.CharField(blank=True, max_length=265, null=True),
                ),
                (
                    "gift_name_fi",
                    models.CharField(blank=True, max_length=265, null=True),
                ),
                (
                    "gift_name_sl",
                    models.CharField(blank=True, max_length=265, null=True),
                ),
                (
                    "gift_name_sq",
                    models.CharField(blank=True, max_length=265, null=True),
                ),
                (
                    "gift_name_am",
                    models.CharField(blank=True, max_length=265, null=True),
                ),
                (
                    "gift_name_hy",
                    models.CharField(blank=True, max_length=265, null=True),
                ),
                (
                    "gift_name_la",
                    models.CharField(blank=True, max_length=265, null=True),
                ),
                (
                    "gift_name_lv",
                    models.CharField(blank=True, max_length=265, null=True),
                ),
                (
                    "gift_name_th",
                    models.CharField(blank=True, max_length=265, null=True),
                ),
                (
                    "gift_name_az",
                    models.CharField(blank=True, max_length=265, null=True),
                ),
                (
                    "gift_name_eu",
                    models.CharField(blank=True, max_length=265, null=True),
                ),
                (
                    "gift_name_be",
                    models.CharField(blank=True, max_length=265, null=True),
                ),
                (
                    "gift_name_bn",
                    models.CharField(blank=True, max_length=265, null=True),
                ),
                (
                    "gift_name_bs",
                    models.CharField(blank=True, max_length=265, null=True),
                ),
                (
                    "gift_name_bg",
                    models.CharField(blank=True, max_length=265, null=True),
                ),
                (
                    "gift_name_km",
                    models.CharField(blank=True, max_length=265, null=True),
                ),
                (
                    "gift_name_ca",
                    models.CharField(blank=True, max_length=265, null=True),
                ),
                (
                    "gift_name_et",
                    models.CharField(blank=True, max_length=265, null=True),
                ),
                (
                    "gift_name_gl",
                    models.CharField(blank=True, max_length=265, null=True),
                ),
                (
                    "gift_name_ka",
                    models.CharField(blank=True, max_length=265, null=True),
                ),
                (
                    "gift_name_hi",
                    models.CharField(blank=True, max_length=265, null=True),
                ),
                (
                    "gift_name_hu",
                    models.CharField(blank=True, max_length=265, null=True),
                ),
                (
                    "gift_name_is",
                    models.CharField(blank=True, max_length=265, null=True),
                ),
                (
                    "gift_name_id",
                    models.CharField(blank=True, max_length=265, null=True),
                ),
                (
                    "gift_name_ga",
                    models.CharField(blank=True, max_length=265, null=True),
                ),
                (
                    "gift_name_mk",
                    models.CharField(blank=True, max_length=265, null=True),
                ),
                (
                    "gift_name_mn",
                    models.CharField(blank=True, max_length=265, null=True),
                ),
                (
                    "gift_name_ne",
                    models.CharField(blank=True, max_length=265, null=True),
                ),
                (
                    "gift_name_ro",
                    models.CharField(blank=True, max_length=265, null=True),
                ),
                (
                    "gift_name_sr",
                    models.CharField(blank=True, max_length=265, null=True),
                ),
                (
                    "gift_name_sk",
                    models.CharField(blank=True, max_length=265, null=True),
                ),
                (
                    "gift_name_ta",
                    models.CharField(blank=True, max_length=265, null=True),
                ),
                (
                    "gift_name_tg",
                    models.CharField(blank=True, max_length=265, null=True),
                ),
                (
                    "gift_name_tr",
                    models.CharField(blank=True, max_length=265, null=True),
                ),
                (
                    "gift_name_ur",
                    models.CharField(blank=True, max_length=265, null=True),
                ),
                (
                    "gift_name_uz",
                    models.CharField(blank=True, max_length=265, null=True),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="VirtualGift",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gift_name", models.CharField(max_length=100)),
                ("cost", models.FloatField()),
                (
                    "picture",
                    models.ImageField(
                        blank=True, upload_to=gifts.models.AbstractGift.get_avatar_path
                    ),
                ),
                ("gift_name_fr", models.CharField(max_length=100)),
                (
                    "gift_name_zh_cn",
                    models.CharField(blank=True, max_length=265, null=True),
                ),
                (
                    "gift_name_nl",
                    models.CharField(blank=True, max_length=265, null=True),
                ),
                (
                    "gift_name_de",
                    models.CharField(blank=True, max_length=265, null=True),
                ),
                (
                    "gift_name_sw",
                    models.CharField(blank=True, max_length=265, null=True),
                ),
                (
                    "gift_name_it",
                    models.CharField(blank=True, max_length=265, null=True),
                ),
                (
                    "gift_name_ar",
                    models.CharField(blank=True, max_length=265, null=True),
                ),
                (
                    "gift_name_iw",
                    models.CharField(blank=True, max_length=265, null=True),
                ),
                (
                    "gift_name_ja",
                    models.CharField(blank=True, max_length=265, null=True),
                ),
                (
                    "gift_name_ru",
                    models.CharField(blank=True, max_length=265, null=True),
                ),
                (
                    "gift_name_fa",
                    models.CharField(blank=True, max_length=265, null=True),
                ),
                (
                    "gift_name_pt_br",
                    models.CharField(blank=True, max_length=265, null=True),
                ),
                (
                    "gift_name_pt_pt",
                    models.CharField(blank=True, max_length=265, null=True),
                ),
                (
                    "gift_name_es",
                    models.CharField(blank=True, max_length=265, null=True),
                ),
                (
                    "gift_name_el",
                    models.CharField(blank=True, max_length=265, null=True),
                ),
                (
                    "gift_name_zh_tw",
                    models.CharField(blank=True, max_length=265, null=True),
                ),
                (
                    "gift_name_uk",
                    models.CharField(blank=True, max_length=265, null=True),
                ),
                (
                    "gift_name_ko",
                    models.CharField(blank=True, max_length=265, null=True),
                ),
                (
                    "gift_name_pl",
                    models.CharField(blank=True, max_length=265, null=True),
                ),
                (
                    "gift_name_vi",
                    models.CharField(blank=True, max_length=265, null=True),
                ),
                (
                    "gift_name_no",
                    models.CharField(blank=True, max_length=265, null=True),
                ),
                (
                    "gift_name_sv",
                    models.CharField(blank=True, max_length=265, null=True),
                ),
                (
                    "gift_name_hr",
                    models.CharField(blank=True, max_length=265, null=True),
                ),
                (
                    "gift_name_cs",
                    models.CharField(blank=True, max_length=265, null=True),
                ),
                (
                    "gift_name_da",
                    models.CharField(blank=True, max_length=265, null=True),
                ),
                (
                    "gift_name_tl",
                    models.CharField(blank=True, max_length=265, null=True),
                ),
                (
                    "gift_name_fi",
                    models.CharField(blank=True, max_length=265, null=True),
                ),
                (
                    "gift_name_sl",
                    models.CharField(blank=True, max_length=265, null=True),
                ),
                (
                    "gift_name_sq",
                    models.CharField(blank=True, max_length=265, null=True),
                ),
                (
                    "gift_name_am",
                    models.CharField(blank=True, max_length=265, null=True),
                ),
                (
                    "gift_name_hy",
                    models.CharField(blank=True, max_length=265, null=True),
                ),
                (
                    "gift_name_la",
                    models.CharField(blank=True, max_length=265, null=True),
                ),
                (
                    "gift_name_lv",
                    models.CharField(blank=True, max_length=265, null=True),
                ),
                (
                    "gift_name_th",
                    models.CharField(blank=True, max_length=265, null=True),
                ),
                (
                    "gift_name_az",
                    models.CharField(blank=True, max_length=265, null=True),
                ),
                (
                    "gift_name_eu",
                    models.CharField(blank=True, max_length=265, null=True),
                ),
                (
                    "gift_name_be",
                    models.CharField(blank=True, max_length=265, null=True),
                ),
                (
                    "gift_name_bn",
                    models.CharField(blank=True, max_length=265, null=True),
                ),
                (
                    "gift_name_bs",
                    models.CharField(blank=True, max_length=265, null=True),
                ),
                (
                    "gift_name_bg",
                    models.CharField(blank=True, max_length=265, null=True),
                ),
                (
                    "gift_name_km",
                    models.CharField(blank=True, max_length=265, null=True),
                ),
                (
                    "gift_name_ca",
                    models.CharField(blank=True, max_length=265, null=True),
                ),
                (
                    "gift_name_et",
                    models.CharField(blank=True, max_length=265, null=True),
                ),
                (
                    "gift_name_gl",
                    models.CharField(blank=True, max_length=265, null=True),
                ),
                (
                    "gift_name_ka",
                    models.CharField(blank=True, max_length=265, null=True),
                ),
                (
                    "gift_name_hi",
                    models.CharField(blank=True, max_length=265, null=True),
                ),
                (
                    "gift_name_hu",
                    models.CharField(blank=True, max_length=265, null=True),
                ),
                (
                    "gift_name_is",
                    models.CharField(blank=True, max_length=265, null=True),
                ),
                (
                    "gift_name_id",
                    models.CharField(blank=True, max_length=265, null=True),
                ),
                (
                    "gift_name_ga",
                    models.CharField(blank=True, max_length=265, null=True),
                ),
                (
                    "gift_name_mk",
                    models.CharField(blank=True, max_length=265, null=True),
                ),
                (
                    "gift_name_mn",
                    models.CharField(blank=True, max_length=265, null=True),
                ),
                (
                    "gift_name_ne",
                    models.CharField(blank=True, max_length=265, null=True),
                ),
                (
                    "gift_name_ro",
                    models.CharField(blank=True, max_length=265, null=True),
                ),
                (
                    "gift_name_sr",
                    models.CharField(blank=True, max_length=265, null=True),
                ),
                (
                    "gift_name_sk",
                    models.CharField(blank=True, max_length=265, null=True),
                ),
                (
                    "gift_name_ta",
                    models.CharField(blank=True, max_length=265, null=True),
                ),
                (
                    "gift_name_tg",
                    models.CharField(blank=True, max_length=265, null=True),
                ),
                (
                    "gift_name_tr",
                    models.CharField(blank=True, max_length=265, null=True),
                ),
                (
                    "gift_name_ur",
                    models.CharField(blank=True, max_length=265, null=True),
                ),
                (
                    "gift_name_uz",
                    models.CharField(blank=True, max_length=265, null=True),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
