# Generated by Django 3.1.5 on 2022-11-25 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gifts", "0013_realgift_virtualgift"),
    ]

    operations = [
        migrations.AlterField(
            model_name="giftpurchase",
            name="gift",
            field=models.CharField(max_length=500),
        ),
    ]
