# Generated by Django 3.1.5 on 2022-11-25 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gifts", "0014_auto_20221125_1330"),
    ]

    operations = [
        migrations.AlterField(
            model_name="realgift",
            name="gift_name_fr",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="virtualgift",
            name="gift_name_fr",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
