# Generated by Django 3.1.5 on 2022-11-25 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("gifts", "0017_auto_20221125_1713"),
    ]

    operations = [
        migrations.AlterField(
            model_name="giftpurchase",
            name="gift",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gift_for_giftpurchase",
                to="gifts.allgifts",
            ),
        ),
    ]
