# Generated by Django 3.1.5 on 2023-08-13 18:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0019_realgiftpriceforregion_virtualgiftpriceforregion'),
    ]

    operations = [
        migrations.AddField(
            model_name='realgift',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='virtualgift',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
