# Generated by Django 3.1.5 on 2022-12-09 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0004_purchase_payment_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="currency",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
