# Generated by Django 3.1.5 on 2022-12-12 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0005_purchase_currency"),
    ]

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(default="", max_length=255)),
                ("price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("is_on_discount", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "validity",
                    models.CharField(
                        choices=[
                            ("PERWEEK", "PER WEEK"),
                            ("PERMONTH", "PER MONTH"),
                            ("PER3MONTH", "PER 3 MONTH"),
                            ("PER6MONTH", "PER 6 MONTH"),
                            ("PERYEAR", "PER YEAR"),
                        ],
                        default="PERMONTH",
                        max_length=100,
                    ),
                ),
                (
                    "dicounted_price",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="purchase.package",
                    ),
                ),
            ],
        ),
    ]
