# Generated by Django 3.1.5 on 2022-12-12 12:01

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0006_plan"),
    ]

    operations = [
        migrations.AddField(
            model_name="packagepurchase",
            name="cancelled_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="packagepurchase",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(2022, 12, 12, 12, 1, 59, 433586, tzinfo=utc),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="packagepurchase",
            name="downgraded_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="packagepurchase",
            name="downgraded_to_package",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="downgraded_package",
                to="purchase.package",
            ),
        ),
        migrations.AddField(
            model_name="packagepurchase",
            name="ends_at",
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name="packagepurchase",
            name="package_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="packagepurchase",
            name="plan",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="plan",
                to="purchase.plan",
            ),
        ),
        migrations.AddField(
            model_name="packagepurchase",
            name="purchase_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="packagepurchase",
            name="renewed_subscription",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="renewed_package",
                to="purchase.packagepurchase",
            ),
        ),
        migrations.AddField(
            model_name="packagepurchase",
            name="rennewed_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="packagepurchase",
            name="starts_at",
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name="packagepurchase",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="packagepurchase",
            name="upgraded_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="packagepurchase",
            name="upgraded_to_package",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="upgraded_package",
                to="purchase.package",
            ),
        ),
        migrations.AlterField(
            model_name="package",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="package",
            name="price",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="plan",
            name="dicounted_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=12, null=True
            ),
        ),
    ]
