# Generated by Django 3.1.5 on 2022-12-13 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0008_auto_20221212_1309"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="package",
            name="price",
        ),
    ]
