# Generated by Django 3.1.5 on 2022-12-13 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0009_remove_package_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="packagepurchase",
            name="created_by_admin",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
