# Generated by Django 3.1.5 on 2022-12-13 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0010_packagepurchase_created_by_admin"),
    ]

    operations = [
        migrations.CreateModel(
            name="Permission",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "description",
                    models.CharField(
                        blank=True, default=None, max_length=255, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Package Permission",
                "verbose_name_plural": "Package Permissions",
            },
        ),
        migrations.AddField(
            model_name="package",
            name="permissions",
            field=models.ManyToManyField(blank=True, to="purchase.Permission"),
        ),
    ]
