# Generated by Django 3.1.5 on 2022-12-21 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0011_auto_20221213_1430"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plan",
            name="dicounted_price",
        ),
        migrations.RemoveField(
            model_name="plan",
            name="price",
        ),
        migrations.AddField(
            model_name="plan",
            name="dicounted_price_in_coins",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="plan",
            name="price_in_coins",
            field=models.IntegerField(default=0, verbose_name="Coins"),
        ),
        migrations.AlterField(
            model_name="packagepurchase",
            name="package_price",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="packagepurchase",
            name="purchase_price",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
