# Generated by Django 3.1.5 on 2022-12-23 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0012_auto_20221221_1153"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="packagepurchase",
            options={
                "verbose_name": "Package Purchase",
                "verbose_name_plural": "Package Purchases",
            },
        ),
        migrations.CreateModel(
            name="PackageTranslation",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=65)),
                ("language_code", models.CharField(max_length=5)),
                (
                    "package",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="package",
                        to="purchase.package",
                    ),
                ),
            ],
        ),
    ]
