# Generated by Django 3.1.5 on 2022-12-23 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0013_auto_20221223_1439"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="name_am",
            field=models.CharField(blank=True, max_length=65, null=True),
        ),
        migrations.AddField(
            model_name="package",
            name="name_ar",
            field=models.CharField(blank=True, max_length=65, null=True),
        ),
        migrations.AddField(
            model_name="package",
            name="name_az",
            field=models.CharField(blank=True, max_length=65, null=True),
        ),
        migrations.AddField(
            model_name="package",
            name="name_be",
            field=models.CharField(blank=True, max_length=65, null=True),
        ),
        migrations.AddField(
            model_name="package",
            name="name_bg",
            field=models.CharField(blank=True, max_length=65, null=True),
        ),
        migrations.AddField(
            model_name="package",
            name="name_bn",
            field=models.CharField(blank=True, max_length=65, null=True),
        ),
        migrations.AddField(
            model_name="package",
            name="name_br",
            field=models.CharField(blank=True, max_length=65, null=True),
        ),
        migrations.AddField(
            model_name="package",
            name="name_bs",
            field=models.CharField(blank=True, max_length=65, null=True),
        ),
        migrations.AddField(
            model_name="package",
            name="name_ca",
            field=models.CharField(blank=True, max_length=65, null=True),
        ),
        migrations.AddField(
            model_name="package",
            name="name_cs",
            field=models.CharField(blank=True, max_length=65, null=True),
        ),
        migrations.AddField(
            model_name="package",
            name="name_da",
            field=models.CharField(blank=True, max_length=65, null=True),
        ),
        migrations.AddField(
            model_name="package",
            name="name_de",
            field=models.CharField(blank=True, max_length=65, null=True),
        ),
        migrations.AddField(
            model_name="package",
            name="name_el",
            field=models.CharField(blank=True, max_length=65, null=True),
        ),
        migrations.AddField(
            model_name="package",
            name="name_es",
            field=models.CharField(blank=True, max_length=65, null=True),
        ),
        migrations.AddField(
            model_name="package",
            name="name_es_419",
            field=models.CharField(blank=True, max_length=65, null=True),
        ),
        migrations.AddField(
            model_name="package",
            name="name_et",
            field=models.CharField(blank=True, max_length=65, null=True),
        ),
        migrations.AddField(
            model_name="package",
            name="name_eu",
            field=models.CharField(blank=True, max_length=65, null=True),
        ),
        migrations.AddField(
            model_name="package",
            name="name_fa",
            field=models.CharField(blank=True, max_length=65, null=True),
        ),
        migrations.AddField(
            model_name="package",
            name="name_fi",
            field=models.CharField(blank=True, max_length=65, null=True),
        ),
        migrations.AddField(
            model_name="package",
            name="name_fr",
            field=models.CharField(blank=True, max_length=65, null=True),
        ),
        migrations.AddField(
            model_name="package",
            name="name_ga",
            field=models.CharField(blank=True, max_length=65, null=True),
        ),
        migrations.AddField(
            model_name="package",
            name="name_gl",
            field=models.CharField(blank=True, max_length=65, null=True),
        ),
        migrations.AddField(
            model_name="package",
            name="name_hi",
            field=models.CharField(blank=True, max_length=65, null=True),
        ),
        migrations.AddField(
            model_name="package",
            name="name_hr",
            field=models.CharField(blank=True, max_length=65, null=True),
        ),
        migrations.AddField(
            model_name="package",
            name="name_hu",
            field=models.CharField(blank=True, max_length=65, null=True),
        ),
        migrations.AddField(
            model_name="package",
            name="name_hy",
            field=models.CharField(blank=True, max_length=65, null=True),
        ),
        migrations.AddField(
            model_name="package",
            name="name_id",
            field=models.CharField(blank=True, max_length=65, null=True),
        ),
        migrations.AddField(
            model_name="package",
            name="name_is",
            field=models.CharField(blank=True, max_length=65, null=True),
        ),
        migrations.AddField(
            model_name="package",
            name="name_it",
            field=models.CharField(blank=True, max_length=65, null=True),
        ),
        migrations.AddField(
            model_name="package",
            name="name_iw",
            field=models.CharField(blank=True, max_length=65, null=True),
        ),
        migrations.AddField(
            model_name="package",
            name="name_ja",
            field=models.CharField(blank=True, max_length=65, null=True),
        ),
        migrations.AddField(
            model_name="package",
            name="name_ka",
            field=models.CharField(blank=True, max_length=65, null=True),
        ),
        migrations.AddField(
            model_name="package",
            name="name_km",
            field=models.CharField(blank=True, max_length=65, null=True),
        ),
        migrations.AddField(
            model_name="package",
            name="name_ko",
            field=models.CharField(blank=True, max_length=65, null=True),
        ),
        migrations.AddField(
            model_name="package",
            name="name_la",
            field=models.CharField(blank=True, max_length=65, null=True),
        ),
        migrations.AddField(
            model_name="package",
            name="name_lv",
            field=models.CharField(blank=True, max_length=65, null=True),
        ),
        migrations.AddField(
            model_name="package",
            name="name_mk",
            field=models.CharField(blank=True, max_length=65, null=True),
        ),
        migrations.AddField(
            model_name="package",
            name="name_mn",
            field=models.CharField(blank=True, max_length=65, null=True),
        ),
        migrations.AddField(
            model_name="package",
            name="name_ne",
            field=models.CharField(blank=True, max_length=65, null=True),
        ),
        migrations.AddField(
            model_name="package",
            name="name_nl",
            field=models.CharField(blank=True, max_length=65, null=True),
        ),
        migrations.AddField(
            model_name="package",
            name="name_nn",
            field=models.CharField(blank=True, max_length=65, null=True),
        ),
        migrations.AddField(
            model_name="package",
            name="name_no",
            field=models.CharField(blank=True, max_length=65, null=True),
        ),
        migrations.AddField(
            model_name="package",
            name="name_pl",
            field=models.CharField(blank=True, max_length=65, null=True),
        ),
        migrations.AddField(
            model_name="package",
            name="name_pt_br",
            field=models.CharField(blank=True, max_length=65, null=True),
        ),
        migrations.AddField(
            model_name="package",
            name="name_pt_pt",
            field=models.CharField(blank=True, max_length=65, null=True),
        ),
        migrations.AddField(
            model_name="package",
            name="name_ro",
            field=models.CharField(blank=True, max_length=65, null=True),
        ),
        migrations.AddField(
            model_name="package",
            name="name_ru",
            field=models.CharField(blank=True, max_length=65, null=True),
        ),
        migrations.AddField(
            model_name="package",
            name="name_sk",
            field=models.CharField(blank=True, max_length=65, null=True),
        ),
        migrations.AddField(
            model_name="package",
            name="name_sl",
            field=models.CharField(blank=True, max_length=65, null=True),
        ),
        migrations.AddField(
            model_name="package",
            name="name_sq",
            field=models.CharField(blank=True, max_length=65, null=True),
        ),
        migrations.AddField(
            model_name="package",
            name="name_sr",
            field=models.CharField(blank=True, max_length=65, null=True),
        ),
        migrations.AddField(
            model_name="package",
            name="name_sv",
            field=models.CharField(blank=True, max_length=65, null=True),
        ),
        migrations.AddField(
            model_name="package",
            name="name_sw",
            field=models.CharField(blank=True, max_length=65, null=True),
        ),
        migrations.AddField(
            model_name="package",
            name="name_ta",
            field=models.CharField(blank=True, max_length=65, null=True),
        ),
        migrations.AddField(
            model_name="package",
            name="name_tg",
            field=models.CharField(blank=True, max_length=65, null=True),
        ),
        migrations.AddField(
            model_name="package",
            name="name_th",
            field=models.CharField(blank=True, max_length=65, null=True),
        ),
        migrations.AddField(
            model_name="package",
            name="name_tl",
            field=models.CharField(blank=True, max_length=65, null=True),
        ),
        migrations.AddField(
            model_name="package",
            name="name_tr",
            field=models.CharField(blank=True, max_length=65, null=True),
        ),
        migrations.AddField(
            model_name="package",
            name="name_uk",
            field=models.CharField(blank=True, max_length=65, null=True),
        ),
        migrations.AddField(
            model_name="package",
            name="name_ur",
            field=models.CharField(blank=True, max_length=65, null=True),
        ),
        migrations.AddField(
            model_name="package",
            name="name_uz",
            field=models.CharField(blank=True, max_length=65, null=True),
        ),
        migrations.AddField(
            model_name="package",
            name="name_vi",
            field=models.CharField(blank=True, max_length=65, null=True),
        ),
        migrations.AddField(
            model_name="package",
            name="name_zh_cn",
            field=models.CharField(blank=True, max_length=65, null=True),
        ),
        migrations.AddField(
            model_name="package",
            name="name_zh_tw",
            field=models.CharField(blank=True, max_length=65, null=True),
        ),
        migrations.DeleteModel(
            name="PackageTranslation",
        ),
    ]
