# Generated by Django 3.1.5 on 2022-12-26 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0016_auto_20221223_1702"),
    ]

    operations = [
        migrations.CreateModel(
            name="PermissionLimit",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("per_day", models.IntegerField()),
                ("per_month", models.IntegerField()),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="package_limit",
                        to="purchase.package",
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permission_limit",
                        to="purchase.permission",
                    ),
                ),
            ],
        ),
    ]
