# Generated by Django 3.1.5 on 2022-12-26 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0017_permissionlimit"),
    ]

    operations = [
        migrations.AddField(
            model_name="permissionlimit",
            name="name",
            field=models.CharField(blank=True, max_length=65, null=True),
        ),
    ]
