# Generated by Django 3.1.5 on 2022-12-26 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0018_permissionlimit_name"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PermissionLimit",
            new_name="PackagePermissionLimit",
        ),
    ]
