# Generated by Django 3.1.5 on 2022-12-26 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0019_auto_20221226_0936"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PackagePermissionLimit",
            new_name="PackageLimit",
        ),
    ]
