# Generated by Django 3.1.5 on 2022-12-26 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0020_auto_20221226_0944"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="package",
            name="permissions",
        ),
        migrations.AddField(
            model_name="packagelimit",
            name="description",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
