# Generated by Django 3.1.5 on 2022-12-26 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0021_auto_20221226_0957"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PackageLimit",
            new_name="PackagePermissionLimit",
        ),
    ]
