# Generated by Django 3.1.5 on 2022-12-26 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0023_packagepermissionlimit_is_unlimited"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="packagepermissionlimit",
            options={
                "verbose_name": "Package Permission Limit",
                "verbose_name_plural": "Package Permission Limits",
            },
        ),
        migrations.AddField(
            model_name="package",
            name="permissions",
            field=models.ManyToManyField(blank=True, to="purchase.Permission"),
        ),
    ]
