# Generated by Django 3.1.5 on 2022-12-26 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0024_auto_20221226_1200"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="packagepermissionlimit",
            name="description",
        ),
        migrations.RemoveField(
            model_name="packagepermissionlimit",
            name="name",
        ),
        migrations.AddField(
            model_name="packagepermissionlimit",
            name="per_week",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="packagepermissionlimit",
            name="package",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="package",
                to="purchase.package",
            ),
        ),
        migrations.AlterField(
            model_name="packagepermissionlimit",
            name="permission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="permission",
                to="purchase.permission",
            ),
        ),
    ]
