# Generated by Django 3.1.5 on 2022-12-28 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0025_auto_20221226_1314"),
    ]

    operations = [
        migrations.AddField(
            model_name="permission",
            name="user_free_limit",
            field=models.IntegerField(
                blank=True, default=0, verbose_name="User free daily limit"
            ),
        ),
    ]
