# Generated by Django 3.1.5 on 2022-12-29 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0027_auto_20221229_0827"),
    ]

    operations = [
        migrations.AlterField(
            model_name="packagepermissionlimit",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="packagepermissionlimit",
            name="per_day",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="packagepermissionlimit",
            name="per_month",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="packagepermissionlimit",
            name="per_week",
            field=models.IntegerField(default=0),
        ),
    ]
