# Generated by Django 3.1.5 on 2023-01-12 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0029_auto_20230102_1055"),
    ]

    operations = [
        migrations.CreateModel(
            name="CoinPrices",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("coins_count", models.IntegerField(default=0)),
                ("original_price", models.FloatField()),
                ("discounted_price", models.FloatField()),
                ("is_active", models.BooleanField(default=True)),
                ("currency", models.CharField(default="EUR", max_length=50)),
            ],
            options={
                "verbose_name": "Coin Prices",
                "verbose_name_plural": "Coin Prices",
            },
        ),
    ]
