# Generated by Django 3.1.5 on 2023-02-04 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0030_coinprices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="permission",
            name="name",
            field=models.CharField(
                choices=[
                    ("SHARE_MOMENT", "SHARE_MOMENT"),
                    ("SHARE_USER_LOCATION", "SHARE_USER_LOCATION"),
                    (
                        "REQUEST_USER_PRIVATE_ALBUM_ACCESS",
                        "REQUEST_USER_PRIVATE_ALBUM_ACCESS",
                    ),
                    ("SHARE_STORY", "SHARE_STORY"),
                    ("FIRST_FREE_MESSAGE", "FIRST_FREE_MESSAGE"),
                ],
                max_length=255,
                unique=True,
            ),
        ),
    ]
