# Generated by Django 3.1.5 on 2023-02-07 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0046_auto_20230206_1809'),
        ('purchase', '0031_auto_20230204_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinPricesForRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coins_count', models.IntegerField(default=0)),
                ('original_price', models.FloatField()),
                ('discounted_price', models.FloatField()),
                ('coin_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.coinprices')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.coinsettingsregion')),
            ],
        ),
    ]
