# Generated by Django 3.1.5 on 2023-02-08 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0046_auto_20230206_1809'),
        ('purchase', '0032_coinpricesforregion'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanForRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_in_coins', models.IntegerField(default=0, verbose_name='Coins')),
                ('is_active', models.BooleanField(default=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.plan')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.coinsettingsregion')),
            ],
        ),
    ]
