# Generated by Django 3.1.5 on 2023-02-11 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0033_planforregion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='name',
            field=models.CharField(choices=[('SHARE_MOMENT', 'SHARE_MOMENT'), ('SHARE_USER_LOCATION', 'SHARE_USER_LOCATION'), ('REQUEST_USER_PRIVATE_ALBUM_ACCESS', 'REQUEST_USER_PRIVATE_ALBUM_ACCESS'), ('SHARE_STORY', 'SHARE_STORY'), ('FIRST_FREE_MESSAGE', 'FIRST_FREE_MESSAGE'), ('RANDOM_SEARCHED_USER_RESULTS_LIMIT', 'RANDOM_SEARCHED_USER_RESULTS_LIMIT'), ('POPULAR_SEARCHED_USER_RESULTS_LIMIT', 'POPULAR_SEARCHED_USER_RESULTS_LIMIT'), ('MOST_ACTIVE_SEARCHED_USER_RESULTS_LIMIT', 'MOST_ACTIVE_SEARCHED_USER_RESULTS_LIMIT')], max_length=255, unique=True),
        ),
    ]
