# Generated by Django 3.1.5 on 2022-04-29 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_notification_notificationsettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationsettings",
            name="message",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
