# Generated by Django 3.1.5 on 2022-04-29 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_added_notificationsettings_message"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ("-timestamp",)},
        ),
    ]
