# Generated by Django 3.1.5 on 2022-04-30 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_added_ordering_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationsettings",
            name="id",
            field=models.CharField(max_length=25, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="notificationsettings",
            name="message",
            field=models.CharField(max_length=70, null=True),
        ),
    ]
