# Generated by Django 3.1.5 on 2022-05-02 03:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chat", "0005_changed_id_message_notificationsettings"),
    ]

    operations = [
        migrations.RenameField(
            model_name="notificationsettings",
            old_name="message",
            new_name="message_str",
        ),
        migrations.RemoveField(
            model_name="message",
            name="deleted",
        ),
        migrations.AddField(
            model_name="room",
            name="deleted",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="FirstMessage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.CharField(blank=True, max_length=512)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "by_user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="FMCreate_By",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Broadcast",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.CharField(blank=True, max_length=512)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "by_user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Create_By",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
