# Generated by Django 3.1.5 on 2022-05-13 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0006_auto_20220502_0906"),
    ]

    operations = [
        migrations.AddField(
            model_name="broadcast",
            name="deleted",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
