# Generated by Django 3.1.5 on 2022-06-03 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0008_notes"),
        ("chat", "0008_auto_20220602_1802"),
    ]

    operations = []
