# Generated by Django 3.1.5 on 2022-06-04 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0009_merge_20220603_1511"),
    ]

    operations = [
        migrations.AddField(
            model_name="notes",
            name="forRealUser",
            field=models.BooleanField(default=False),
        ),
    ]
