# Generated by Django 3.1.5 on 2022-06-14 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0010_notes_forrealuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessageimages",
            name="upload_type",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
