# Generated by Django 3.1.5 on 2022-10-13 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0011_chatmessageimages_upload_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chats",
            fields=[],
            options={
                "verbose_name": "Chat",
                "verbose_name_plural": "Chats",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("chat.room",),
        ),
    ]
