# Generated by Django 3.1.5 on 2022-10-19 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0012_chats"),
    ]

    operations = [
        migrations.AddField(
            model_name="broadcast",
            name="content_fr",
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name="firstmessage",
            name="content_fr",
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name="notification",
            name="notification_body_fr",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="notificationsettings",
            name="message_str_fr",
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name="notificationsettings",
            name="title_fr",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
