# Generated by Django 3.1.5 on 2022-11-21 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0015_auto_20221119_0914"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="content",
            field=models.CharField(blank=True, max_length=5120),
        ),
    ]
