# Generated by Django 3.1.5 on 2022-11-23 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0017_auto_20221122_1610"),
    ]

    operations = [
        migrations.AddField(
            model_name="broadcast",
            name="content_ga",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="broadcast",
            name="content_hi",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="broadcast",
            name="content_hu",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="broadcast",
            name="content_id",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="broadcast",
            name="content_is",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="broadcast",
            name="content_mk",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="broadcast",
            name="content_mn",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="broadcast",
            name="content_ne",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="broadcast",
            name="content_ro",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="broadcast",
            name="content_sk",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="broadcast",
            name="content_sr",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="broadcast",
            name="content_ta",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="broadcast",
            name="content_tg",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="broadcast",
            name="content_tr",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="broadcast",
            name="content_ur",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="broadcast",
            name="content_uz",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="firstmessage",
            name="content_ga",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="firstmessage",
            name="content_hi",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="firstmessage",
            name="content_hu",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="firstmessage",
            name="content_id",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="firstmessage",
            name="content_is",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="firstmessage",
            name="content_mk",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="firstmessage",
            name="content_mn",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="firstmessage",
            name="content_ne",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="firstmessage",
            name="content_ro",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="firstmessage",
            name="content_sk",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="firstmessage",
            name="content_sr",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="firstmessage",
            name="content_ta",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="firstmessage",
            name="content_tg",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="firstmessage",
            name="content_tr",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="firstmessage",
            name="content_ur",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="firstmessage",
            name="content_uz",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
    ]
