# Generated by Django 3.1.5 on 2022-11-24 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0018_auto_20221123_0956"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="message_type",
            field=models.CharField(
                choices=[("C", "CONVERSATIONAL"), ("G", "GIFT_MESSAGE")],
                default="C",
                max_length=10,
            ),
        ),
    ]
