# Generated by Django 3.1.5 on 2022-12-07 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0023_deletedmessagedate"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="private_photo_request_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="message",
            name="message_type",
            field=models.CharField(
                choices=[
                    ("C", "CONVERSATIONAL"),
                    ("G", "GIFT_MESSAGE"),
                    ("P", "PrivatePhotoRequest"),
                ],
                default="C",
                max_length=10,
            ),
        ),
    ]
