# Generated by Django 3.1.5 on 2022-12-08 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0024_auto_20221207_1519"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="message_type",
            field=models.CharField(
                choices=[
                    ("C", "CONVERSATIONAL"),
                    ("G", "GIFT_MESSAGE"),
                    ("P", "PrivatePhotoRequest"),
                    ("GL", "GEO_LOCATION"),
                ],
                default="C",
                max_length=10,
            ),
        ),
    ]
