# Generated by Django 3.1.5 on 2023-01-21 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0025_auto_20221208_1431"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="message_type",
            field=models.CharField(
                choices=[
                    ("C", "CONVERSATIONAL"),
                    ("G", "GIFT_MESSAGE"),
                    ("P", "PrivatePhotoRequest"),
                    ("GL", "GEO_LOCATION"),
                    ("CM", "CUSTOM_MESSAGE"),
                ],
                default="C",
                max_length=10,
            ),
        ),
    ]
