# Generated by Django 3.1.5 on 2023-02-03 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0028_freemessagelimit"),
    ]

    operations = [
        migrations.RenameField(
            model_name="freemessagelimit",
            old_name="number",
            new_name="user",
        ),
    ]
