# Generated by Django 3.1.5 on 2023-07-03 18:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserSubscriptionPlan',
            new_name='ModeratorSubscriptionPlan',
        ),
    ]
