# Generated by Django 3.1.5 on 2023-07-03 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_auto_20230703_1833'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moderatorsubscriptionplan',
            old_name='user',
            new_name='moderator',
        ),
    ]
