# Generated by Django 3.1.5 on 2022-10-17 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("defaultPicker", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Language",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("language", models.CharField(max_length=10)),
                ("language_code", models.CharField(max_length=5)),
            ],
            options={
                "verbose_name": "language",
                "verbose_name_plural": "language",
            },
        ),
    ]
