# Generated by Django 3.1.5 on 2022-11-18 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("defaultPicker", "0003_auto_20221117_1328"),
    ]

    operations = [
        migrations.AddField(
            model_name="family",
            name="familyPlans_ar",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="family",
            name="familyPlans_br",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="family",
            name="familyPlans_cs",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="family",
            name="familyPlans_da",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="family",
            name="familyPlans_de",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="family",
            name="familyPlans_el",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="family",
            name="familyPlans_es",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="family",
            name="familyPlans_es_419",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="family",
            name="familyPlans_fa",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="family",
            name="familyPlans_fi",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="family",
            name="familyPlans_hr",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="family",
            name="familyPlans_it",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="family",
            name="familyPlans_iw",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="family",
            name="familyPlans_ja",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="family",
            name="familyPlans_ko",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="family",
            name="familyPlans_nl",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="family",
            name="familyPlans_nn",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="family",
            name="familyPlans_no",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="family",
            name="familyPlans_pl",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="family",
            name="familyPlans_pt_br",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="family",
            name="familyPlans_pt_pt",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="family",
            name="familyPlans_ru",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="family",
            name="familyPlans_sl",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="family",
            name="familyPlans_sv",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="family",
            name="familyPlans_sw",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="family",
            name="familyPlans_tl",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="family",
            name="familyPlans_uk",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="family",
            name="familyPlans_vi",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="family",
            name="familyPlans_zh_cn",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="family",
            name="familyPlans_zh_tw",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="searchgender",
            name="searchGender_ar",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="searchgender",
            name="searchGender_br",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="searchgender",
            name="searchGender_cs",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="searchgender",
            name="searchGender_da",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="searchgender",
            name="searchGender_de",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="searchgender",
            name="searchGender_el",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="searchgender",
            name="searchGender_es",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="searchgender",
            name="searchGender_es_419",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="searchgender",
            name="searchGender_fa",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="searchgender",
            name="searchGender_fi",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="searchgender",
            name="searchGender_hr",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="searchgender",
            name="searchGender_it",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="searchgender",
            name="searchGender_iw",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="searchgender",
            name="searchGender_ja",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="searchgender",
            name="searchGender_ko",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="searchgender",
            name="searchGender_nl",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="searchgender",
            name="searchGender_nn",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="searchgender",
            name="searchGender_no",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="searchgender",
            name="searchGender_pl",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="searchgender",
            name="searchGender_pt_br",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="searchgender",
            name="searchGender_pt_pt",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="searchgender",
            name="searchGender_ru",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="searchgender",
            name="searchGender_sl",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="searchgender",
            name="searchGender_sv",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="searchgender",
            name="searchGender_sw",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="searchgender",
            name="searchGender_tl",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="searchgender",
            name="searchGender_uk",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="searchgender",
            name="searchGender_vi",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="searchgender",
            name="searchGender_zh_cn",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="searchgender",
            name="searchGender_zh_tw",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
    ]
