# Generated by Django 3.1.5 on 2022-11-23 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("defaultPicker", "0007_auto_20221119_1020"),
    ]

    operations = [
        migrations.AddField(
            model_name="ethnicity",
            name="ethnicity_ga",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="ethnicity",
            name="ethnicity_hi",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="ethnicity",
            name="ethnicity_hu",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="ethnicity",
            name="ethnicity_id",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="ethnicity",
            name="ethnicity_is",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="ethnicity",
            name="ethnicity_mk",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="ethnicity",
            name="ethnicity_mn",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="ethnicity",
            name="ethnicity_ne",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="ethnicity",
            name="ethnicity_ro",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="ethnicity",
            name="ethnicity_sk",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="ethnicity",
            name="ethnicity_sr",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="ethnicity",
            name="ethnicity_ta",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="ethnicity",
            name="ethnicity_tg",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="ethnicity",
            name="ethnicity_tr",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="ethnicity",
            name="ethnicity_ur",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="ethnicity",
            name="ethnicity_uz",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="family",
            name="familyPlans_ga",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="family",
            name="familyPlans_hi",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="family",
            name="familyPlans_hu",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="family",
            name="familyPlans_id",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="family",
            name="familyPlans_is",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="family",
            name="familyPlans_mk",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="family",
            name="familyPlans_mn",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="family",
            name="familyPlans_ne",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="family",
            name="familyPlans_ro",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="family",
            name="familyPlans_sk",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="family",
            name="familyPlans_sr",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="family",
            name="familyPlans_ta",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="family",
            name="familyPlans_tg",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="family",
            name="familyPlans_tr",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="family",
            name="familyPlans_ur",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="family",
            name="familyPlans_uz",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="gender",
            name="gender_ga",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="gender",
            name="gender_hi",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="gender",
            name="gender_hu",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="gender",
            name="gender_id",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="gender",
            name="gender_is",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="gender",
            name="gender_mk",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="gender",
            name="gender_mn",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="gender",
            name="gender_ne",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="gender",
            name="gender_ro",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="gender",
            name="gender_sk",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="gender",
            name="gender_sr",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="gender",
            name="gender_ta",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="gender",
            name="gender_tg",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="gender",
            name="gender_tr",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="gender",
            name="gender_ur",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="gender",
            name="gender_uz",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="politics",
            name="politics_ga",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="politics",
            name="politics_hi",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="politics",
            name="politics_hu",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="politics",
            name="politics_id",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="politics",
            name="politics_is",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="politics",
            name="politics_mk",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="politics",
            name="politics_mn",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="politics",
            name="politics_ne",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="politics",
            name="politics_ro",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="politics",
            name="politics_sk",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="politics",
            name="politics_sr",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="politics",
            name="politics_ta",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="politics",
            name="politics_tg",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="politics",
            name="politics_tr",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="politics",
            name="politics_ur",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="politics",
            name="politics_uz",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="religious",
            name="religious_ga",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="religious",
            name="religious_hi",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="religious",
            name="religious_hu",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="religious",
            name="religious_id",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="religious",
            name="religious_is",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="religious",
            name="religious_mk",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="religious",
            name="religious_mn",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="religious",
            name="religious_ne",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="religious",
            name="religious_ro",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="religious",
            name="religious_sk",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="religious",
            name="religious_sr",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="religious",
            name="religious_ta",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="religious",
            name="religious_tg",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="religious",
            name="religious_tr",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="religious",
            name="religious_ur",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="religious",
            name="religious_uz",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="searchgender",
            name="searchGender_ga",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="searchgender",
            name="searchGender_hi",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="searchgender",
            name="searchGender_hu",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="searchgender",
            name="searchGender_id",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="searchgender",
            name="searchGender_is",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="searchgender",
            name="searchGender_mk",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="searchgender",
            name="searchGender_mn",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="searchgender",
            name="searchGender_ne",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="searchgender",
            name="searchGender_ro",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="searchgender",
            name="searchGender_sk",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="searchgender",
            name="searchGender_sr",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="searchgender",
            name="searchGender_ta",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="searchgender",
            name="searchGender_tg",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="searchgender",
            name="searchGender_tr",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="searchgender",
            name="searchGender_ur",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="searchgender",
            name="searchGender_uz",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="tags",
            name="tag_ga",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="tags",
            name="tag_hi",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="tags",
            name="tag_hu",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="tags",
            name="tag_id",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="tags",
            name="tag_is",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="tags",
            name="tag_mk",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="tags",
            name="tag_mn",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="tags",
            name="tag_ne",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="tags",
            name="tag_ro",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="tags",
            name="tag_sk",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="tags",
            name="tag_sr",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="tags",
            name="tag_ta",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="tags",
            name="tag_tg",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="tags",
            name="tag_tr",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="tags",
            name="tag_ur",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="tags",
            name="tag_uz",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="zodiacsign",
            name="zodiacSign_ga",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="zodiacsign",
            name="zodiacSign_hi",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="zodiacsign",
            name="zodiacSign_hu",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="zodiacsign",
            name="zodiacSign_id",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="zodiacsign",
            name="zodiacSign_is",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="zodiacsign",
            name="zodiacSign_mk",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="zodiacsign",
            name="zodiacSign_mn",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="zodiacsign",
            name="zodiacSign_ne",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="zodiacsign",
            name="zodiacSign_ro",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="zodiacsign",
            name="zodiacSign_sk",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="zodiacsign",
            name="zodiacSign_sr",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="zodiacsign",
            name="zodiacSign_ta",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="zodiacsign",
            name="zodiacSign_tg",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="zodiacsign",
            name="zodiacSign_tr",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="zodiacsign",
            name="zodiacSign_ur",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
        migrations.AddField(
            model_name="zodiacsign",
            name="zodiacSign_uz",
            field=models.CharField(blank=True, max_length=265, null=True),
        ),
    ]
