# Generated by Django 3.1.5 on 2023-07-15 17:22

from django.db import migrations

def add_third_gender(apps, schema_editor):
    gender = apps.get_model("defaultPicker", "gender")
    if not gender.objects.filter(id=3).exists():
        third_gender = gender.objects.create(gender="Prefer not to say")
        if not third_gender.id==3:
            third_gender.id = 3
            third_gender.save()
            gender.objects.filter(id__gt=3).delete()
    elif not gender.objects.get(id=3).gender=="Prefer not to say":
        third_gender = gender.objects.get(id=3)
        third_gender.gender = "Prefer not to say"
        third_gender.save()
    if gender.objects.filter(id__gt=3).exists():
        gender.objects.filter(id__gt=3).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('defaultPicker', '0008_auto_20221123_0947'),
    ]

    operations = [
         migrations.RunPython(add_third_gender),
    ]
