# Generated by Django 3.1.5 on 2023-08-17 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defaultPicker', '0009_auto_20230715_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='country_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
