# Generated by Django 3.1.5 on 2023-04-12 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificationsetting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationsound',
            name='name',
            field=models.CharField(choices=[('coin_purchase', 'Coin Purchase'), ('package_purchase', 'Package Purchase'), ('gift_purchase', 'Gift Purchase'), ('new_user', 'New User'), ('report_user', 'Report User'), ('report_moment', 'Report Moment'), ('notification', 'Notification')], max_length=255),
        ),
    ]
