# Generated by Django 3.1.5 on 2023-04-12 17:43

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificationsetting', '0002_auto_20230412_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationsound',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='D:\\Freelance work\\i69 project\\i69-api-Fix-real_users_api\\staticfiles'), upload_to='admin/sound/'),
        ),
        migrations.AlterField(
            model_name='notificationsound',
            name='name',
            field=models.CharField(choices=[('coin_purchase', 'Coin Purchase'), ('package_purchase', 'Package Purchase'), ('gift_purchase', 'Gift Purchase'), ('new_user', 'New User'), ('report_user', 'Report User'), ('report_moment', 'Report Moment'), ('notification', 'Notification')], max_length=255, unique=True),
        ),
    ]
