# Generated by Django 3.1.5 on 2023-04-12 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificationsetting', '0003_auto_20230412_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationsound',
            name='file',
            field=models.FileField(upload_to='admin/sound/'),
        ),
    ]
