# Generated by Django 3.1.5 on 2022-04-18 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="gift_coins_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="purchase_coins_date",
            field=models.DateTimeField(null=True),
        ),
    ]
