# Generated by Django 3.1.5 on 2022-04-19 08:40

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_auto_20220419_0436"),
    ]

    operations = [
        migrations.CreateModel(
            name="CoinsHistorys",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("user.user",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name="user",
            name="gift_coins_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="purchase_coins_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
