# Generated by Django 3.1.5 on 2022-05-02 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_auto_20220419_1410"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="broadcast_deleted_upto",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="broadcast_read_upto",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="firstmessage_read_upto",
            field=models.IntegerField(default=0),
        ),
    ]
