# Generated by Django 3.1.5 on 2022-05-16 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_auto_20220502_0906"),
    ]

    operations = [
        migrations.DeleteModel(
            name="WorkerInvitation",
        ),
    ]
