# Generated by Django 3.1.5 on 2022-10-15 02:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0012_chatsque"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatsque",
            name="worker",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_active_worker",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
