# Generated by Django 3.1.5 on 2022-10-15 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0014_chatsquesetting"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatsquesetting",
            name="intervalPeriod",
            field=models.CharField(
                choices=[
                    ("Days", "Days"),
                    ("Hours", "Hours"),
                    ("Minutes", "Minutes"),
                    ("Seconds", "Seconds"),
                ],
                max_length=100,
            ),
        ),
    ]
