# Generated by Django 3.1.5 on 2022-10-17 09:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0016_auto_20221015_0757"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chatsque",
            options={"ordering": ("date_created",)},
        ),
        migrations.CreateModel(
            name="ModeratorOnlineScheduler",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("online_time", models.DateTimeField(blank=True, null=True)),
                ("ofline_time", models.DateTimeField(blank=True, null=True)),
                (
                    "moderator_list",
                    models.ManyToManyField(
                        blank=True,
                        limit_choices_to={"roles": "MODERATOR"},
                        null=True,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
