# Generated by Django 3.1.5 on 2022-10-18 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0020_user_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="moderatoronlinescheduler",
            name="list_name",
            field=models.CharField(default=1, max_length=70),
            preserve_default=False,
        ),
    ]
