# Generated by Django 3.1.5 on 2022-10-18 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0022_auto_20221018_1204"),
    ]

    operations = [
        migrations.RenameField(
            model_name="moderatoronlinescheduler",
            old_name="ofline_time",
            new_name="offline_time",
        ),
    ]
