# Generated by Django 3.1.5 on 2022-10-24 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("defaultPicker", "0002_language"),
        ("user", "0023_auto_20221018_1325"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="address",
            field=models.CharField(blank=True, default="", max_length=555),
        ),
        migrations.AddField(
            model_name="user",
            name="language_id_code",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.RemoveField(
            model_name="user",
            name="language",
        ),
        migrations.AddField(
            model_name="user",
            name="language",
            field=models.ManyToManyField(blank=True, to="defaultPicker.language"),
        ),
    ]
