# Generated by Django 3.1.5 on 2022-10-26 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("defaultPicker", "0002_language"),
        ("user", "0025_auto_20221024_1542"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="language",
            field=models.ManyToManyField(blank=True, to="defaultPicker.language"),
        ),
    ]
