# Generated by Django 3.1.5 on 2022-10-28 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("defaultPicker", "0002_language"),
        ("user", "0026_auto_20221026_1326"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="distance",
            field=models.CharField(
                blank=True, default="", editable=False, max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="language",
            field=models.ManyToManyField(blank=True, to="defaultPicker.language"),
        ),
    ]
