# Generated by Django 3.1.5 on 2022-10-29 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("defaultPicker", "0002_language"),
        ("user", "0027_auto_20221028_1429"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="language",
            field=models.ManyToManyField(blank=True, to="defaultPicker.language"),
        ),
    ]
