# Generated by Django 3.1.5 on 2022-10-31 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("defaultPicker", "0002_language"),
        ("user", "0029_auto_20221031_1527"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="language",
            field=models.ManyToManyField(blank=True, to="defaultPicker.language"),
        ),
    ]
