# Generated by Django 3.1.5 on 2022-11-29 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0032_moderatorqscheduler"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userlimit",
            name="action_name",
            field=models.CharField(
                choices=[
                    ("Stories", "Stories"),
                    ("Moments", "Moments"),
                    ("MultiStoryLimit", "MultiStoryLimit"),
                ],
                max_length=95,
                unique=True,
            ),
        ),
    ]
