# Generated by Django 3.1.5 on 2022-12-05 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0034_auto_20221202_1109"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blockedimagealternatives",
            name="action",
            field=models.CharField(
                choices=[
                    ("BLOCKED_IMG", "BLOCKED_IMG"),
                    ("IF_NO_IMAGE", "IF_NO_IMAGE"),
                    ("FEMALE", "FEMALE"),
                    ("MALE", "MALE"),
                    ("PREFER_NOT_TO_SAY", "PREFER_NOT_TO_SAY"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="userlimit",
            name="action_name",
            field=models.CharField(
                choices=[
                    ("Stories", "Stories"),
                    ("Moments", "Moments"),
                    ("MultiStoryLimit", "MultiStoryLimit"),
                    ("FreeProfilePhotos", "FreeProfilePhotos"),
                ],
                max_length=95,
                unique=True,
            ),
        ),
    ]
