# Generated by Django 3.1.5 on 2022-12-07 11:41

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0035_auto_20221205_1747"),
    ]

    operations = [
        migrations.CreateModel(
            name="GiftedCoins",
            fields=[],
            options={
                "verbose_name": "Gifted Coin",
                "verbose_name_plural": "Gifted Coins",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("user.user",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="PurchasedCoins",
            fields=[],
            options={
                "verbose_name": "Purchased Coin",
                "verbose_name_plural": "Purchased Coins",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("user.user",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="country",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="country_code",
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
