# Generated by Django 3.1.5 on 2022-12-06 16:57

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0035_auto_20221205_1747"),
    ]

    operations = [
        migrations.CreateModel(
            name="GiftedCoins",
            fields=[],
            options={
                "verbose_name": "Gifted Coin",
                "verbose_name_plural": "Gifted Coins",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("user.user",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="PurchasedCoins",
            fields=[],
            options={
                "verbose_name": "Purchased Coin",
                "verbose_name_plural": "Purchased Coins",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("user.user",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="PrivateUserPhoto",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.ImageField(
                        blank=True, null=True, upload_to=user.models.content_file_name
                    ),
                ),
                ("file_url", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="private_avatar_photos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
