# Generated by Django 3.1.5 on 2022-12-07 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0036_giftedcoins_privateuserphoto_purchasedcoins"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrivatePhotoViewTime",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("no_of_hours", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="PrivatePhotoViewRequest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("A", "APPROVE"), ("R", "REJECT"), ("P", "PENDING")],
                        default="P",
                        max_length=10,
                    ),
                ),
                (
                    "requested_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requested_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_to_view",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_to_view",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
