# Generated by Django 3.1.5 on 2022-12-07 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0037_privatephotoviewrequest_privatephotoviewtime"),
        ("user", "0036_auto_20221207_1141"),
    ]

    operations = []
