# Generated by Django 3.1.5 on 2022-12-08 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0038_merge_20221207_1819"),
    ]

    operations = [
        migrations.AddField(
            model_name="privateuserphoto",
            name="is_admin_approved",
            field=models.BooleanField(default=False),
        ),
    ]
