# Generated by Django 3.1.5 on 2022-12-10 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0039_privateuserphoto_is_admin_approved"),
    ]

    operations = [
        migrations.AlterField(
            model_name="privatephotoviewrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("A", "APPROVE"),
                    ("R", "REJECT"),
                    ("P", "PENDING"),
                    ("C", "CANCEL"),
                ],
                default="P",
                max_length=10,
            ),
        ),
    ]
