# Generated by Django 3.1.5 on 2023-01-02 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0041_auto_20230102_1055"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="city",
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="state",
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
