# Generated by Django 3.1.5 on 2023-01-04 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0042_auto_20230102_1616"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="notified_count",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
