# Generated by Django 3.1.5 on 2023-01-05 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0043_user_notified_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="notification_sent",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
