# Generated by Django 3.1.5 on 2023-02-06 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0045_auto_20230204_1931"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coinsettings",
            name="region",
        ),
        migrations.CreateModel(
            name="CoinSettingsForRegion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("coins_needed", models.IntegerField()),
                (
                    "coinsettings",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.coinsettings",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.coinsettingsregion",
                    ),
                ),
            ],
        ),
    ]
