# Generated by Django 3.1.5 on 2023-02-09 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0046_auto_20230206_1809'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeleteAccountSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete_account_allowed', models.BooleanField(default=True)),
            ],
        ),
    ]
