# Generated by Django 3.1.5 on 2023-02-09 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0047_deleteaccountsetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinsettingsregion',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
