# Generated by Django 3.1.5 on 2023-02-18 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('push_notifications', '0009_alter_apnsdevice_device_id'),
        ('user', '0048_auto_20230209_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailedFCMMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_message', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('gcm_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='push_notifications.gcmdevice')),
            ],
        ),
    ]
