# Generated by Django 3.1.5 on 2023-02-23 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0050_profilefollow'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('visiting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_visiting', to=settings.AUTH_USER_MODEL)),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_visitor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
