# Generated by Django 3.1.5 on 2023-02-24 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0051_profilevisit'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('feature_type', models.CharField(max_length=255, unique=True)),
                ('feature_status', models.PositiveSmallIntegerField(choices=[(0, 'OFF'), (1, 'ON')], default=0)),
            ],
            options={
                'verbose_name': 'Feature Setting',
                'verbose_name_plural': 'Feature Settings',
            },
        ),
    ]
