# Generated by Django 3.1.5 on 2023-02-24 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0053_coinspendinghistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coinspendinghistory',
            options={'verbose_name': 'Coin Spending History', 'verbose_name_plural': 'Coin Spending History'},
        ),
    ]
