# Generated by Django 3.1.5 on 2023-03-03 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0057_auto_20230303_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofiletranlations',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
