# Generated by Django 3.1.5 on 2023-03-06 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0058_userprofiletranlations_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinterestedin',
            name='str_name',
            field=models.CharField(max_length=95, null=True, unique=True),
        ),
    ]
