# Generated by Django 3.1.5 on 2023-03-06 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0059_userinterestedin_str_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinterestedin',
            name='str_name',
            field=models.CharField(blank=True, max_length=95, null=True),
        ),
    ]
