# Generated by Django 3.1.5 on 2023-04-06 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0066_auto_20230321_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
