# Generated by Django 3.1.5 on 2023-04-10 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0067_country_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserForModsRestriction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restricted_user_for_mods', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
