# Generated by Django 3.1.5 on 2023-04-10 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0068_userformodsrestriction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userformodsrestriction',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='restricted_user_for_mods', to=settings.AUTH_USER_MODEL),
        ),
    ]
