# Generated by Django 3.1.5 on 2023-04-11 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0069_auto_20230410_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Male'), (1, 'Female'), (2, 'Prefer not to say'), (3, 'Select your gender')], null=True),
        ),
    ]
