# Generated by Django 3.1.5 on 2023-04-13 11:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0070_auto_20230411_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='userformodsrestriction',
            name='moderators',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
