# Generated by Django 3.1.5 on 2023-04-13 12:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0071_userformodsrestriction_moderators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userformodsrestriction',
            name='moderators',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
