# Generated by Django 3.1.5 on 2023-07-10 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0073_auto_20230429_1350'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatsque',
            options={'ordering': ('-isAssigned', 'date_created')},
        ),
    ]
