# Generated by Django 3.1.5 on 2023-07-11 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0074_auto_20230710_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='paste_access',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
