# Generated by Django 3.1.5 on 2023-07-12 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0076_user_zip_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allow_manual_chat',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
