# Generated by Django 3.1.5 on 2023-07-20 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0077_user_allow_manual_chat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='allow_manual_chat',
        ),
        migrations.RemoveField(
            model_name='user',
            name='paste_access',
        ),
    ]
