# Generated by Django 3.1.5 on 2023-08-12 12:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0078_auto_20230720_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='userphoto',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
