# Generated by Django 3.1.5 on 2023-08-17 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0078_auto_20230817_1318'),
        ('user', '0080_auto_20230812_1305'),
    ]

    operations = [
    ]
