# Generated by Django 3.1.5 on 2023-08-18 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0081_merge_20230817_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='paste_access',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
