# Generated by Django 3.1.5 on 2023-08-30 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0082_user_paste_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilevisit',
            name='last_visited_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.RunSQL(
            'UPDATE user_profilevisit set last_visited_at = created_at'
        )
    ]
