# Generated by Django 3.1.5 on 2023-09-12 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0085_user_facebook_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='deleteaccountsetting',
            name='retain_data_for_days',
            field=models.IntegerField(default=90),
        ),
        migrations.AddField(
            model_name='user',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='user_deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
