# Generated by Django 3.1.5 on 2023-09-30 12:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0086_auto_20230912_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsquesetting',
            name='allow_offline_mods',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='moderatoronlinescheduler',
            name='moderator_list',
            field=models.ManyToManyField(blank=True, related_name='moderator_schedule', to=settings.AUTH_USER_MODEL),
        ),
    ]
