# Generated by Django 3.1.5 on 2023-11-29 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0087_auto_20230930_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='note',
            field=models.TextField(default=''),
        ),
    ]
