# Generated by Django 3.1.5 on 2023-12-07 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0088_user_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='note',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
