# Generated by Django 3.1.5 on 2023-12-12 18:38

from django.db import migrations


def remove_duplicates(apps, schema_editor):
    ProfileVisit = apps.get_model('user', 'ProfileVisit')
    profile_visits = ProfileVisit.objects.all().order_by('-created_at')
    seen_visits = set()
    for pv in profile_visits:
        if f"{pv.visitor} {pv.visiting}" in seen_visits:
            pv.delete()

        seen_visits.add(f"{pv.visitor} {pv.visiting}")


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0089_auto_20231207_1815'),
    ]

    operations = [
        migrations.RunPython(remove_duplicates),
        migrations.AlterUniqueTogether(
            name='profilevisit',
            unique_together={('visitor', 'visiting')},
        ),
    ]
