PIC_REVIEW_NOTIFICATION_SETTING = 'USERPICREVIEW'

SCHEDULE_STORY_COINS = 'SCHEDULE_STORY_COINS'
POST_STORY_COINS = 'POST_STORY_COINS'
SCHEDULE_MOMENT_COINS = 'SCHEDULE_MOMENT_COINS'
POST_MOMENT_COINS = 'POST_MOMENT_COINS'

SHARE_STORY_PERMISSION = 'SHARE_STORY'
SHARE_MOMENT_PERMISSION = 'SHARE_MOMENT'